name: autogis
channels:
  - conda-forge
dependencies:
  - python=3.12
  - bokeh=3.10.0
  - cartopy=0.26.0
  - contextily=1.7.1
  - fiona=1.10.1
  - folium=0.20.0
  - geojson=3.3.0
  - geopandas=1.2.0
  - geopy=2.5.0
  - ipykernel=7.4.0
  - ipywidgets=8.1.9
  - jupyterlab=4.6.4
  - jupyterlab-git=0.54.1
  - jupyterlab-myst=2.7.0
  - jupytext=1.19.5
  - mapclassify=2.11.0
  - matplotlib=3.11.2
  - myst-nb=1.4.0
  - nbsphinx=0.9.8
  - networkx=3.7
  - numpy=2.5.3
  - osmnx=2.1.1
  - owslib=0.36.0
  - pandas=2.3.3
  - pillow=12.3.0
  - plotly=7.1.0
  - psycopg2=2.9.13
  - pyogrio=0.13.0
  - pyproj=3.8.0
  - pyrosm=0.15.0
  - rasterio=1.5.1
  - requests=2.34.2
  - rioxarray=0.23.0
  - scikit-learn=1.9.1
  - scipy=1.18.1
  - seaborn=0.13.2
  - shapely=2.1.2
  - sphinx=9.1.0
  - sphinx-book-theme=1.4.0
  - sqlalchemy=2.1.2
  - xarray=2026.9.0
  - pip
  - pip:
      - bokeh-sampledata==2025.0
      - mpl_chord_diagram==0.4.1
      - tilemapbase==0.4.7
