name: autogis-environment

channels:
  - conda-forge

dependencies:
  - python=3.7
  - geopandas
  - pyproj=2.4.0
  - geopy
  - geojson
  - bokeh
  - contextily
  - matplotlib
  - folium
  - mplleaflet
  - geoplot
  - osmnx
